Q.1) SOLITION BELOW

NumPy (Numerical Python) is a foundational library in Python that provides a high-performance, multidimensional array object and tools for working with these arrays. It’s widely used in scientific computing, data analysis, and machine learning. Here’s how NumPy enhances Python’s capabilities:

1. Efficient Multidimensional Arrays
Purpose: At the core of NumPy is the ndarray (n-dimensional array), a fast, flexible container for large datasets.
Advantages: NumPy arrays are much more memory-efficient and perform faster for operations than standard Python lists, especially for large data sets, because they store data in contiguous memory blocks and have fewer memory allocations.
2. Performance and Speed
Purpose: NumPy leverages highly optimized C and Fortran code for mathematical operations.
Advantages: Operations on NumPy arrays can be up to 10-100x faster than equivalent operations on standard Python lists. This efficiency makes NumPy suitable for scientific applications that require heavy computation.
3. Vectorization and Broadcasting
Purpose: NumPy enables vectorized operations, which apply operations to entire arrays rather than needing explicit loops.
Advantages: Vectorization and broadcasting lead to cleaner, more concise code and often avoid the need for looping, which reduces execution time. Broadcasting allows operations on arrays of different shapes without extensive reshaping, adding flexibility in computations.
4. Mathematical Functions and Statistical Tools
Purpose: NumPy provides a large library of mathematical functions (e.g., trigonometric, logarithmic) and statistical functions.
Advantages: This extensive function library enables quick, reliable calculations over entire arrays or subsets, aiding in data analysis and statistical tasks directly within Python.
5. Interoperability with Other Libraries
Purpose: Many libraries for scientific computing (e.g., SciPy, pandas, scikit-learn) are built on top of NumPy.
Advantages: This interoperability ensures consistency and enables easy integration of specialized tools with NumPy arrays, allowing a seamless flow in complex data workflows.
6. Support for Linear Algebra and Random Sampling
Purpose: NumPy includes built-in functions for linear algebra (e.g., matrix operations, eigenvalues) and random sampling (e.g., generating random numbers from various distributions).
Advantages: These features are essential for machine learning, statistical analysis, and simulations, making NumPy a comprehensive tool for scientific computing.

Q.2) SOLUTION BELOW.

Both np.mean() and np.average() are used to calculate the average of values in a NumPy array, but they have distinct features and use cases:

1. np.mean()
Purpose: np.mean() calculates the arithmetic mean (simple average) of elements along a specified axis.
Syntax: np.mean(array, axis=None, dtype=None, out=None)
Key Feature: np.mean() does not support weighted averages; it treats each element with equal weight.


Example

In [ ]:
import numpy as np
array = np.array([1, 2, 3, 4])
mean = np.mean(array)

When to Use: Use np.mean() when you want the simple average of an array and do not need to apply different weights to elements.
2. np.average()
Purpose: np.average() calculates a weighted average of the elements.
Syntax: np.average(array, axis=None, weights=None, returned=False)
Key Feature: It has an optional weights parameter, allowing you to assign different weights to elements in the calculation.
If weights is not provided, it behaves like np.mean() and calculates the simple average.

Example

In [ ]:
array = np.array([1, 2, 3, 4])
weights = np.array([1, 2, 3, 4])  # Heavier weights for larger values
weighted_avg = np.average(array, weights=weights)

Q.3) SOLUTION BELOW

In NumPy, arrays can be reversed along various axes using slicing, functions, and specific methods. Here are several methods to reverse NumPy arrays, with examples for both 1D and 2D arrays.

Reversing a 1D Array


Using Slicing

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

[5 4 3 2 1]


Using np.flip()

In [ ]:
reversed_arr = np.flip(arr)
print(reversed_arr)

[5 4 3 2 1]


 Both methods reverse the 1D array entirely.


 Reversing a 2D Array
For 2D arrays, you can reverse along different axes: row-wise, column-wise, or both.

Reversing Entire Array (Both Axes)

This reverses the entire 2D array, flipping both rows and columns.

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


Reversing Along Rows (Axis 1)

This flips each row independently, so columns are reversed.

In [ ]:
reversed_columns = np.flip(arr_2d, axis=1)
print(reversed_columns)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


Reversing Along Columns (Axis 0)

This flips each column independently, so rows are reversed

In [ ]:
reversed_rows = np.flip(arr_2d, axis=0)
print(reversed_rows)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


Using Slicing for 2D Arrays

Slicing can be used similarly, where [::-1] reverses the array along the specified axis.

In [ ]:
reversed_columns = arr_2d[:, ::-1]  # Reverse columns
reversed_rows = arr_2d[::-1, :]    # Reverse rows
print(reversed_columns)
print(reversed_rows)

[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


Q.4) SOLUTION BELOW.

In NumPy, you can determine the data type of elements in an array using the .dtype attribute. This attribute provides information about the data type of the elements contained within the array. Here's how you can use it:

Determining the Data Type of a NumPy Array


Creating a NumPy Array

In [ ]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


Creating Arrays with Specific Data Types You can also specify the data type when creating an array:

In [ ]:
arr_float = np.array([1, 2, 3, 4], dtype=float)
print(arr_float.dtype)

float64


Checking the Data Type of Existing Arrays

In [ ]:
arr_str = np.array(['a', 'b', 'c'])
print(arr_str.dtype)

<U1


Importance of Data Types in Memory Management and Performance
Memory Efficiency

Different data types consume different amounts of memory. For instance, an int32 uses 4 bytes, while an int64 uses 8 bytes. Using smaller data types can significantly reduce memory usage, especially for large arrays. This is crucial in scenarios where memory is limited or when handling large datasets.

Q.5) SOLUTION BELOW

In NumPy, an ndarray (N-dimensional array) is the central data structure. It is a homogeneous array that can hold elements of the same data type and allows for efficient numerical operations on large data sets.

Key Features of ndarray in NumPy

Homogeneity: All elements in an ndarray must be of the same data type (e.g., all integers or all floats), which allows for fast computations and reduced memory usage.

Fixed Size: Once an ndarray is created, its size cannot be changed. This immutability enables better performance as the memory layout can be optimized.
Multidimensional: ndarray objects can have any number of dimensions, making them suitable for working with multi-dimensional data (e.g., 1D arrays for vectors, 2D arrays for matrices, and higher dimensions for tensors).

Efficient Operations: NumPy supports element-wise operations and broadcasting, which allows operations on arrays of different shapes without explicit looping. These features make operations faster compared to standard Python structures.

Built-in Mathematical Functions: NumPy provides a range of optimized mathematical functions (e.g., linear algebra, statistical operations) that can be applied directly to ndarray objects, enabling high-performance scientific computing.


Differences Between ndarray and Standard Python Lists
Data Type Consistency: Python lists can contain elements of mixed data types, while ndarrays are homogeneous, holding elements of a single data type.

Memory Efficiency: ndarray objects are more memory-efficient because they use contiguous blocks of memory and require less overhead to store each element, unlike lists, which store references to objects.

Performance: NumPy arrays are significantly faster than Python lists for large data sets because they are optimized for numerical operations and use lower-level implementations (like C).

Indexing and Slicing: Both lists and ndarrays support indexing and slicing, but ndarrays provide advanced indexing capabilities, like slicing over multiple dimensions, boolean indexing, and fancy indexing.

Broadcasting: ndarrays support broadcasting, allowing arrays of different shapes to be combined in element-wise operations without looping. Standard lists lack this functionality.
Overall, ndarrays are essential for handling large datasets and performing complex mathematical operations efficiently, making them ideal for scientific computing, machine learning, and data analysis applications.

Q.6) SOLUTION BELOW

When working with large-scale numerical operations, using NumPy arrays instead of Python lists offers several performance advantages. Here's an analysis of why and how NumPy arrays perform better:

1. Memory Efficiency
Python Lists: Lists are collections of pointers to objects, which means each element in a list is a reference to a Python object. This design adds significant memory overhead, especially for large data. Additionally, Python lists are heterogeneous, so they have to account for different data types, leading to even more inefficiency.
NumPy Arrays: NumPy arrays store data in contiguous blocks of memory with a fixed data type (e.g., integers or floats). This reduces memory overhead and allows efficient use of cache memory. Consequently, a NumPy array of a large number of elements occupies much less memory than an equivalent Python list, especially when all elements are of the same type.
2. Vectorized Operations
Python Lists: Applying an operation over each element of a list generally requires a for loop in Python. Each iteration of the loop incurs Python interpreter overhead, making large-scale operations slow.
NumPy Arrays: NumPy allows element-wise operations directly on arrays, a feature called "vectorization." Instead of looping over individual elements, NumPy applies operations on blocks of data at once using optimized C and Fortran code, which is much faster. This results in significant speed-ups for mathematical operations.
3. Lower-Level Code Integration
Python Lists: Python lists rely on the Python interpreter, which introduces more overhead due to its dynamic and interpreted nature. Python operations can’t be optimized as they must handle various data types.
NumPy Arrays: NumPy is built on optimized C and Fortran libraries (like BLAS and LAPACK), so operations on arrays are executed at a much lower level than those on Python lists. This lower-level execution translates to substantial performance gains, particularly for operations like matrix multiplication, linear algebra computations, and statistical functions.
4. Parallelization and SIMD Optimization
Python Lists: Python’s interpreter does not natively support Single Instruction Multiple Data (SIMD) instructions or parallelized operations within lists, limiting its speed.
NumPy Arrays: NumPy takes advantage of SIMD and multicore processing in certain operations (e.g., summing, multiplying elements) on large arrays. Many NumPy operations are parallelized, allowing them to use multiple cores for computation when possible, thereby further boosting performance on modern CPUs.
5. Better Support for Broadcasting
Python Lists: Applying an operation to arrays of different shapes requires explicit looping or padding, which adds complexity and time.
NumPy Arrays: NumPy supports broadcasting, allowing it to perform operations on arrays of different shapes without extra overhead. This feature is highly beneficial for linear algebra, image processing, and scientific computing, as it reduces the need for explicit loops and complex manipulation of array shapes.
Empirical Performance Comparison Example
Consider a large-scale numerical operation, like adding 10 million elements in both a Python list and a NumPy array:

In [ ]:
import time # Import the time module
import numpy as np #Import the numpy module

# Using Python lists
python_list = [i for i in range(10_000_000)]
start = time.time()
python_list = [x + 5 for x in python_list]
print("Python list time:", time.time() - start)

# Using NumPy arrays
numpy_array = np.arange(10_000_000)
start = time.time()
numpy_array += 5
print("NumPy array time:", time.time() - start)

Python list time: 0.882436990737915
NumPy array time: 0.009286880493164062


In this example:

Python List: Requires iterating over each element in Python, resulting in slower performance.
NumPy Array: Adds 5 to all elements at once due to vectorization, yielding a significant speed-up.
Conclusion
For large-scale numerical computations, NumPy arrays offer substantial performance benefits over Python lists due to:

Reduced memory usage,

Faster execution via vectorization,
Efficient lower-level code integration,
Use of parallelization and SIMD,
Broadcasting capabilities for complex operations.
For data-heavy applications (like machine learning, data analysis, or scientific computing), NumPy is a clear choice for performance optimization.

Q.7) SOLUTION BELOW

In NumPy, vstack() and hstack() are functions used to stack arrays vertically and horizontally, respectively. They are part of the numpy module and are particularly useful for combining multiple arrays into one.

1. vstack()
Purpose: Stacks arrays in sequence vertically (row-wise).
Input Requirements: The arrays must have the same shape along all but the first axis.


Example:

In [ ]:
import numpy as np

# Creating two 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stacking vertically
vstack_result = np.vstack((array1, array2))
print("Vertical Stack (1D Arrays):")
print(vstack_result)

# Creating two 2D arrays
array3 = np.array([[1, 2, 3], [4, 5, 6]])
array4 = np.array([[7, 8, 9], [10, 11, 12]])

# Stacking vertically
vstack_2d_result = np.vstack((array3, array4))
print("\nVertical Stack (2D Arrays):")
print(vstack_2d_result)


Vertical Stack (1D Arrays):
[[1 2 3]
 [4 5 6]]

Vertical Stack (2D Arrays):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


hstack()
Purpose: Stacks arrays in sequence horizontally (column-wise).
Input Requirements: The arrays must have the same shape along all but the second axis.

Example:

In [ ]:
import numpy as np

# Creating two 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stacking horizontally
hstack_result = np.hstack((array1, array2))
print("\nHorizontal Stack (1D Arrays):")
print(hstack_result)

# Creating two 2D arrays
array3 = np.array([[1, 2, 3], [4, 5, 6]])
array4 = np.array([[7, 8, 9], [10, 11, 12]])

# Stacking horizontally
hstack_2d_result = np.hstack((array3, array4))
print("\nHorizontal Stack (2D Arrays):")
print(hstack_2d_result)


Horizontal Stack (1D Arrays):
[1 2 3 4 5 6]

Horizontal Stack (2D Arrays):
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Q.8) SOLUTION BELOW

In NumPy, fliplr() and flipud() are functions used to flip arrays along different axes. Here's how they differ:

fliplr()-

Functionality: Flips an array from left to right (horizontally).
Applicable Dimension: Primarily affects 2D arrays (matrices), but can also be used on higher-dimensional arrays, flipping the last axis (the columns).


In [1]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
flipped = np.fliplr(arr)



flipud()

Functionality: Flips an array from up to down (vertically).
Applicable Dimension: Primarily affects 2D arrays, but also applies to higher-dimensional arrays by flipping along the first axis (the rows).


In [2]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
flipped = np.flipud(arr)



Effects on Various Dimensions
2D Arrays: The effects are straightforward as shown in the examples above.

1D Arrays:

fliplr() has no effect because there are no columns to flip.
flipud() behaves the same way as np.flip() for 1D arrays, flipping the array.

Higher-Dimensional Arrays:

For arrays with more than 2 dimensions, both functions will apply to the respective last axes, flipping along the specified direction. For instance, if you have a 3D array, fliplr() flips the last axis while flipud() flips the first axis.
Example of a 3D array:

Q.9) SOLUTION BELOW

The array_split() method in NumPy is used to split an array into multiple sub-arrays along a specified axis. Here’s an overview of its functionality and how it handles uneven splits:

Functionality of array_split()

Basic Usage:

The method takes an array and a number of sections (or indices) to split it into.
It can be used with multi-dimensional arrays, specifying the axis along which to split.

Syntax:

In [5]:
numpy.array_split(ary, indices_or_sections, axis=0)


NameError: name 'numpy' is not defined

ary: The input array to be split.
indices_or_sections: The number of equal parts to split the array into or a sequence of indices at which to split.
axis: The axis along which to split (default is 0).

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
result = np.array_split(arr, 3)


Handling Uneven Splits
When the array cannot be evenly divided into the specified number of sections, array_split() handles this gracefully by distributing the leftover elements among the resulting sub-arrays.

Example of Uneven Splits

In [8]:
arr = np.array([1, 2, 3, 4, 5])
result = np.array_split(arr, 3)



In this case:

The first two sub-arrays get 2 elements each.

The last sub-array receives the remaining element.

Q.10) SOLUTION BELOW

Vectorization and broadcasting are two key concepts in NumPy that greatly enhance the efficiency of array operations. Here’s a detailed explanation of each:

Vectorization
Concept:
 Vectorization refers to the process of replacing explicit loops with array operations. Instead of iterating through array elements one at a time using Python loops, you can perform operations on entire arrays at once.

Benefits:

Performance:

 Vectorized operations are typically implemented in compiled C code, making them much faster than equivalent operations performed with Python loops.
Simplicity: Code becomes cleaner and easier to read. You can express operations in a more mathematical way, closely resembling the notation you would use in linear algebra.

In [9]:
import numpy as np

# Using a loop
arr = np.array([1, 2, 3, 4])
squared = np.empty(arr.shape)
for i in range(len(arr)):
    squared[i] = arr[i] ** 2

# Vectorized operation
squared_vectorized = arr ** 2



Broadcasting
Concept: Broadcasting is a technique that allows NumPy to perform arithmetic operations on arrays of different shapes. It automatically expands the smaller array across the larger array’s dimensions to make their shapes compatible for element-wise operations.

How It Works:

Compatibility: Two arrays can be broadcast together if their shapes are compatible. Specifically, the dimensions must either be equal or one of them must be 1.
Expansion: When performing operations, NumPy automatically "stretches" the smaller array across the larger one, creating a temporary array that matches the shape of the larger array for the operation.
Example:

In [10]:
import numpy as np

# A 2D array and a 1D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
arr_1d = np.array([10, 20, 30])

# Broadcasting
result = arr_2d + arr_1d



In this example, arr_1d is broadcast to match the shape of arr_2d, allowing for the addition to occur element-wise.

Contributions to Efficient Array Operations
Reduced Computational Overhead: Vectorized operations eliminate the need for explicit loops, which can be slow due to Python’s interpreted nature. This leads to significant performance improvements.

Memory Efficiency: Broadcasting allows for operations without creating large intermediate arrays, as it uses existing data in memory more effectively.

Simplified Code: Both vectorization and broadcasting lead to clearer, more concise code that is easier to maintain and understand.

Support for Complex Operations: They enable the handling of complex mathematical operations over arrays, making NumPy a powerful tool for scientific computing, data analysis, and machine learning.

PRACTICAL QUESTIONS .

Q.1 SOLUTION BELOW

In [12]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

# Print the original array
print("Original Array:")
print(array)

# Interchange rows and columns (transpose the array)
transposed_array = array.T

# Print the transposed array
print("\nTransposed Array:")
print(transposed_array)


Original Array:
[[88 82 61]
 [52 37  3]
 [37  1 67]]

Transposed Array:
[[88 52 37]
 [82 37  1]
 [61  3 67]]


Q.2) SOLUTION BELOW

In [13]:
import numpy as np

# Generate a 1D array with 10 elements
array_1d = np.arange(10)  # This will create an array with values from 0 to 9

# Print the original 1D array
print("Original 1D Array:")
print(array_1d)

# Reshape into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Print the 2x5 array
print("\nReshaped to 2x5 Array:")
print(array_2x5)

# Reshape into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

# Print the 5x2 array
print("\nReshaped to 5x2 Array:")
print(array_5x2)


Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Q.3) SOLUTION BELOW

In [14]:
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Print the original 4x4 array
print("Original 4x4 Array:")
print(array_4x4)

# Add a border of zeros around the array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

# Print the resulting 6x6 array
print("\n6x6 Array with Zero Border:")
print(array_6x6)


Original 4x4 Array:
[[0.88066603 0.76912034 0.51743317 0.5407371 ]
 [0.28258966 0.57629534 0.52454631 0.6196202 ]
 [0.81718093 0.13339302 0.27028783 0.6828639 ]
 [0.74580523 0.52675605 0.692199   0.41738358]]

6x6 Array with Zero Border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.88066603 0.76912034 0.51743317 0.5407371  0.        ]
 [0.         0.28258966 0.57629534 0.52454631 0.6196202  0.        ]
 [0.         0.81718093 0.13339302 0.27028783 0.6828639  0.        ]
 [0.         0.74580523 0.52675605 0.692199   0.41738358 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Q.4) SOUTION BELOW

In [15]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

# Print the resulting array
print(array)


[10 15 20 25 30 35 40 45 50 55 60]


Q.5) SOLUTION BELOW

In [16]:
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase = np.char.upper(array)    # Uppercase
lowercase = np.char.lower(array)    # Lowercase
titlecase = np.char.title(array)    # Title case
capitalize = np.char.capitalize(array)  # Capitalize

# Print the results
print("Original Array:")
print(array)
print("\nUppercase:")
print(uppercase)
print("\nLowercase:")
print(lowercase)
print("\nTitle Case:")
print(titlecase)
print("\nCapitalized:")
print(capitalize)


Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Capitalized:
['Python' 'Numpy' 'Pandas']


Q.6) SOLUTION BELOW

In [17]:
import numpy as np

# Create a NumPy array of words
words = np.array(['hello', 'numpy', 'python', 'data'])

# Insert a space between each character of every word
spaced_words = np.array([' '.join(word) for word in words])

# Print the original and modified arrays
print("Original Array:")
print(words)
print("\nArray with Spaces Between Characters:")
print(spaced_words)


Original Array:
['hello' 'numpy' 'python' 'data']

Array with Spaces Between Characters:
['h e l l o' 'n u m p y' 'p y t h o n' 'd a t a']


Q.7) SOLUTION BELOW

In [18]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise addition
addition = array1 + array2

# Perform element-wise subtraction
subtraction = array1 - array2

# Perform element-wise multiplication
multiplication = array1 * array2

# Perform element-wise division
division = array1 / array2

# Print the results
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition)

print("\nElement-wise Subtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nElement-wise Division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


Q.8) SOLUTION BELOW

In [19]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

# Print the identity matrix and its diagonal elements
print("5x5 Identity Matrix:")
print(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


Q.9) SOLUTION BELOW

In [20]:
import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

# Print the array and the prime numbers found
print("Random Integers Array:")
print(random_integers)

print("\nPrime Numbers in the Array:")
print(prime_numbers)


Random Integers Array:
[998 482  69 738 788 859  39 405 343 449 815 454 663 531 370 143 640 279
 879 144 682 173 111 517 305 191 740 202 882 261 565 252 138 833 265 424
 294  62 590 624 644  58  43 308 329 943 115 751 978 196 311 226  44 755
 759 652 445 782  84 927  47 428 404 530 846 517 824 854 495 472 877 356
  93 530 882 495 804 695 202 226 864 895 975 756  44 266 861 339 575 557
 327  14 796 134 989 612 367 962 155 601]

Prime Numbers in the Array:
[859, 449, 173, 191, 43, 751, 311, 47, 877, 557, 367, 601]


Q.10) SOLTUIN BELOW

In [23]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
# For example, let's use random temperatures between 15 and 35 degrees Celsius
daily_temperatures = np.random.randint(15, 36, size=30)

# Print the daily temperatures
print("Daily Temperatures for the Month:")
print(daily_temperatures)

# Reshape the array into a format that is compatible with the data size
# Since we have 30 days, we can reshape it into a 5x6 or 6x5 matrix, for instance.
# Here, we reshape it into a 5x6 matrix (5 weeks, 6 days per week)
weeks = daily_temperatures.reshape(5, 6)

# Calculate weekly averages
weekly_averages = np.mean(weeks, axis=1)

# Print the weekly averages
print("\nWeekly Averages:")
print(weekly_averages)

Daily Temperatures for the Month:
[33 18 34 20 25 29 29 27 23 19 21 24 23 26 17 29 29 19 22 18 26 31 26 17
 25 24 18 25 28 26]

Weekly Averages:
[26.5        23.83333333 23.83333333 23.33333333 24.33333333]
